### ISSUE TITLE
EKS + Cloud Hosted Router

### ISSUE THREAD

**Issue by bnopacheco** [paocloud/paocloud-aws-terraform#1]
In the article you commented on the CHR/Mikrotik.
Is it possible to use Terraform to provision EKS network output via CHR?

https://medium.com/nexthopthai/provision-aws-eks-cluster-by-terraform-a5f9b2f65b7c
@PayungsakCNR

**Comment by PayungsakCNR** [comment]
Yes , You can set up mikrotik chr virtual router for nat gateway and set up routing table in aws vpc to mikrotik chr , and please make sure disable source/dest check for mikrltik chr network interface.

**Comment by PayungsakCNR** [comment]
Close issue.
